"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import logging
import sys
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from corsheaders.defaults import default_headers, default_methods
import dj_database_url
from bandwar_back.settings import build_logging_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').lower()
IS_PRODUCTION = DJANGO_ENV == 'production'

# Load local env vars only when not running in production.
if not IS_PRODUCTION:
    load_dotenv(BASE_DIR / '.env')

# Helper to require production environment variables.
def get_env_variable(name: str, default=None, required: bool = False):
    value = os.getenv(name, default)
    if required and not value:
        raise ImproperlyConfigured(f"La variable de entorno '{name}' es obligatoria en producción.")
    return value


def parse_env_list(value: str | None):
    if not value:
        return []
    return [item.strip() for item in value.split(',') if item.strip()]

DEFAULT_SECRET_KEY = 'django-insecure-development-key-please-change'
SECRET_KEY = get_env_variable(
    'SECRET_KEY',
    get_env_variable('DJANGO_SECRET_KEY', DEFAULT_SECRET_KEY),
    required=IS_PRODUCTION,
)

DEBUG = os.getenv('DJANGO_DEBUG', os.getenv('DEBUG', 'False')).lower() in ['true', '1', 'yes']

# Permitir explícitamente los dominios usados por Vercel y Back4App para evitar
# rechazos de host y CSRF en despliegues detrás de proxy.
# Emergency mode for Railway deployment: accept all hosts for today only.
# WARNING: This is intentionally permissive to prioritize connectivity for
# the production delivery. Tighten this tomorrow.
ALLOWED_HOSTS = ['*']

# Trust proxy headers so Django sees the correct host/origin behind Back4App/CDN.
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow the Vercel frontend and the Back4App backend domain to be treated as trusted origins for CSRF.
configured_csrf_origins = parse_env_list(os.getenv('CSRF_TRUSTED_ORIGINS', ''))
railway_domains = parse_env_list(os.getenv('RAILWAY_DOMAINS', ''))
railway_public_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN', '')
if railway_public_domain:
    railway_domains.append(
        railway_public_domain if railway_public_domain.startswith(('http://', 'https://')) else f'https://{railway_public_domain}'
    )

default_csrf_origins = [
    'https://bandwar-qzwu6u4su-bandwar-team.vercel.app',
    'https://bandwar-e75s4ztaz-bandwar-team.vercel.app',
    'https://bandwarbackend2-n9gg3px6.b4a.run',
    'https://bandwarbackend2-h9g58o78.b4a.run',
    'https://bandwarbackend1-horglklb.b4a.run',
    'https://bandwarbackend2-6otb95dv.b4a.run',
]

# Also accept the common localhost/dev origins while working locally.
local_csrf_origins = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(configured_csrf_origins + railway_domains + default_csrf_origins + local_csrf_origins))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Librerías externas
    'rest_framework',
    'corsheaders',
    
    # Tu aplicación local
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'bandwar_back.middleware.CorrelationIdMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def build_sqlite_config():
    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


def test_postgres_connection(config: dict) -> bool:
    if config.get('ENGINE') != 'django.db.backends.postgresql':
        return True

    if not config.get('NAME') or not config.get('USER') or not config.get('PASSWORD') or not config.get('HOST'):
        logging.warning('No hay credenciales completas de Postgres; usando SQLite temporalmente.')
        return False

    try:
        import psycopg2
        conn = psycopg2.connect(
            dbname=config.get('NAME'),
            user=config.get('USER'),
            password=config.get('PASSWORD'),
            host=config.get('HOST'),
            port=config.get('PORT'),
            sslmode=config.get('OPTIONS', {}).get('sslmode', 'require' if IS_PRODUCTION else 'prefer'),
            connect_timeout=5,
        )
        conn.close()
        return True
    except Exception as exc:
        logging.warning('No se pudo conectar a Postgres; usando SQLite temporalmente: %s', exc)
        return False


# Configure DATABASES from Railway-provided DATABASE_URL when available.
database_url = os.getenv('DATABASE_URL') or os.getenv('DB_URL')
if database_url:
    try:
        DATABASES = {
            'default': dj_database_url.parse(
                database_url,
                conn_max_age=600,
                ssl_require=IS_PRODUCTION,
            )
        }
    except Exception as exc:
        logging.warning('Error parsing DATABASE_URL; falling back to SQLite: %s', exc)
        DATABASES = build_sqlite_config()
else:
    DATABASES = build_sqlite_config()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'
LOGS_DIR = BASE_DIR / 'logs'
STATIC_ROOT.mkdir(parents=True, exist_ok=True)
MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
LOGS_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = build_logging_config(LOGS_DIR)

# Formato obligatorio para Django 5.0+ y 6.0+
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Django 5/6 requiere DEFAULT_AUTO_FIELD si no se define en apps.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Configuración de CORS (Compartir recursos entre dominios)
# En desarrollo: permite localhost:5173 (Vite React)
# En producción: debe estar en .env
CORS_ALLOWED_ORIGINS = []
# Emergency mode: allow all origins to prioritize connectivity for delivery today.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = []

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'content-type',
    'authorization',
    'x-requested-with',
]
CORS_ALLOW_METHODS = list(default_methods)
CORS_EXPOSE_HEADERS = [
    'Content-Type',
    'Authorization',
]
# Configuración básica de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Usuario personalizado para autenticación mediante Cédula
AUTH_USER_MODEL = 'core.Usuario'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]