"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import logging
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
from corsheaders.defaults import default_headers, default_methods
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').lower()
IS_PRODUCTION = DJANGO_ENV == 'production'

# Load local env vars only when not running in production.
if not IS_PRODUCTION:
    load_dotenv(BASE_DIR / '.env')

# Helper to require production environment variables.
def get_env_variable(name: str, default=None, required: bool = False):
    value = os.getenv(name, default)
    if required and not value:
        raise ImproperlyConfigured(f"La variable de entorno '{name}' es obligatoria en producción.")
    return value

DEFAULT_SECRET_KEY = 'django-insecure-development-key-please-change'
SECRET_KEY = get_env_variable(
    'SECRET_KEY',
    get_env_variable('DJANGO_SECRET_KEY', DEFAULT_SECRET_KEY),
    required=IS_PRODUCTION,
)

DEBUG = os.getenv('DJANGO_DEBUG', os.getenv('DEBUG', 'False')).lower() in ['true', '1', 'yes']

# Si no se configura ALLOWED_HOSTS en el entorno, permitimos todos los hosts
# para evitar rechazos por host inválido en deployments como Back4App.
ALLOWED_HOSTS = [
    host.strip() for host in os.getenv('DJANGO_ALLOWED_HOSTS', os.getenv('ALLOWED_HOSTS', '*')).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Librerías externas
    'rest_framework',
    'corsheaders',
    
    # Tu aplicación local
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def build_sqlite_config():
    return {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


def test_postgres_connection(config: dict) -> bool:
    if config.get('ENGINE') != 'django.db.backends.postgresql':
        return True

    if not config.get('NAME') or not config.get('USER') or not config.get('PASSWORD') or not config.get('HOST'):
        logging.warning('No hay credenciales completas de Postgres; usando SQLite temporalmente.')
        return False

    try:
        import psycopg2
        conn = psycopg2.connect(
            dbname=config.get('NAME'),
            user=config.get('USER'),
            password=config.get('PASSWORD'),
            host=config.get('HOST'),
            port=config.get('PORT'),
            sslmode=config.get('OPTIONS', {}).get('sslmode', 'require' if IS_PRODUCTION else 'prefer'),
            connect_timeout=5,
        )
        conn.close()
        return True
    except Exception as exc:
        logging.warning('No se pudo conectar a Postgres; usando SQLite temporalmente: %s', exc)
        return False


database_url = os.getenv('DATABASE_URL') or os.getenv('DB_URL')
db_engine = os.getenv('DB_ENGINE', '').lower()

if database_url:
    try:
        parsed_db = dj_database_url.parse(
            database_url,
            conn_max_age=600,
            ssl_require=IS_PRODUCTION,
        )
    except Exception as exc:
        logging.warning('No se pudo parsear DATABASE_URL/DB_URL; usando SQLite temporalmente: %s', exc)
        parsed_db = None

    if parsed_db is None:
        DATABASES = build_sqlite_config()
    else:
        if IS_PRODUCTION:
            parsed_db.setdefault('OPTIONS', {})
            parsed_db['OPTIONS'].setdefault('sslmode', 'require')

        if parsed_db.get('ENGINE') == 'django.db.backends.postgresql' and not test_postgres_connection(parsed_db):
            DATABASES = build_sqlite_config()
        else:
            DATABASES = {'default': parsed_db}
elif db_engine == 'sqlite3' or os.getenv('CI', '').lower() in {'1', 'true', 'yes'}:
    DATABASES = build_sqlite_config()
else:
    db_sslmode = os.getenv('DB_SSLMODE', 'require' if IS_PRODUCTION else 'prefer')
    postgres_config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', ''),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': db_sslmode,
        },
    }

    if test_postgres_connection(postgres_config):
        DATABASES = {'default': postgres_config}
    else:
        DATABASES = build_sqlite_config()


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Formato obligatorio para Django 5.0+ y 6.0+
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Django 5/6 requiere DEFAULT_AUTO_FIELD si no se define en apps.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Configuración de CORS (Compartir recursos entre dominios)
# En desarrollo: permite localhost:5173 (Vite React)
# En producción: debe estar en .env
cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [
        origin.strip() for origin in cors_origins_env.split(',')
        if origin.strip()
    ]
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ORIGIN_ALLOW_ALL = False
    CORS_ORIGIN_WHITELIST = CORS_ALLOWED_ORIGINS
else:
    # Si no se define CORS_ALLOWED_ORIGINS, permitimos todas las orígenes
    # para evitar bloqueos de CORS en deployment y facilitar la comunicación
    # entre el frontend desplegado en Vercel y el backend en Back4App.
    CORS_ALLOWED_ORIGINS = []
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ORIGIN_ALLOW_ALL = True
    CORS_ORIGIN_WHITELIST = []

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'content-type',
    'authorization',
    'x-requested-with',
]
CORS_ALLOW_METHODS = list(default_methods)
CORS_EXPOSE_HEADERS = [
    'Content-Type',
    'Authorization',
]
# Configuración básica de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Usuario personalizado para autenticación mediante Cédula
AUTH_USER_MODEL = 'core.Usuario'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]