# Generated by Django 6.0.5 on 2026-05-31 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_instrumento_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisorInteraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_visualizacion_segundos', models.IntegerField()),
                ('puntos_calientes_visitados', models.JSONField(default=list)),
                ('rotaciones_realizadas', models.IntegerField()),
                ('zooms_realizados', models.IntegerField()),
                ('fecha_interaccion', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_visor', to='core.usuario')),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones_visor', to='core.instrumento')),
            ],
            options={
                'verbose_name': 'Visor Interacción',
            },
        ),
    ]
