# Generated by Django 6.0.5 on 2026-06-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fix_django_admin_log_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='carrera',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rango_militar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='semestre',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
