# Generated by Django 6.0.5 on 2026-06-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario_carrera_usuario_rango_militar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumento',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Instrumento'},
        ),
        migrations.AddField(
            model_name='instrumento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='descripcion',
            field=models.TextField(blank=True, default='', help_text='Detalles técnicos del instrumento'),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='modelo_3d_url',
            field=models.CharField(blank=True, help_text='Ruta al archivo .glb (ej: /assets/models/tambor.glb)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='archivo_3d',
            field=models.CharField(blank=True, help_text='[DEPRECATED] Usar modelo_3d_url', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('En reparación', 'En reparación'), ('Mantenimiento', 'Mantenimiento'), ('No operativo', 'No operativo')], default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='tipo',
            field=models.CharField(choices=[('Viento', 'Viento'), ('Percusión', 'Percusión'), ('Cuerda', 'Cuerda'), ('Metales', 'Metales')], default='Viento', max_length=50),
        ),
        migrations.AddIndex(
            model_name='instrumento',
            index=models.Index(fields=['numero_serie'], name='core_instru_numero__ca4ead_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumento',
            index=models.Index(fields=['estado'], name='core_instru_estado_a3c195_idx'),
        ),
        migrations.AddIndex(
            model_name='instrumento',
            index=models.Index(fields=['usuario'], name='core_instru_usuario_3506da_idx'),
        ),
    ]
