# Generated by Django 6.0.5 on 2026-06-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_instrumento_options_instrumento_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='archivo_3d',
        ),
    ]
