# Generated by Django 6.0.5 on 2026-06-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_mantenimiento_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Asignado', 'Asignado'), ('En reparación', 'En reparación'), ('Mantenimiento', 'Mantenimiento'), ('En Taller', 'En Taller'), ('Dañado', 'Dañado'), ('Extraviado', 'Extraviado'), ('No operativo', 'No operativo')], default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='nombre',
            field=models.CharField(choices=[('Bombo', 'Bombo'), ('Platillos', 'Platillos'), ('Lira', 'Lira'), ('Redoblante', 'Redoblante'), ('Granaderos', 'Granaderos'), ('Tambor Mayor', 'Tambor Mayor'), ('Trompeta', 'Trompeta')], max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instrumento_asignado',
            field=models.CharField(blank=True, choices=[('Bombo', 'Bombo'), ('Platillos', 'Platillos'), ('Lira', 'Lira'), ('Redoblante', 'Redoblante'), ('Granaderos', 'Granaderos'), ('Tambor Mayor', 'Tambor Mayor'), ('Trompeta', 'Trompeta')], max_length=50, null=True),
        ),
    ]
