# Generated by Django 6.0.5 on 2026-06-20 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_instrumento_estado_alter_instrumento_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='ultimo_alumno_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ultimos_instrumentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
