# Generated by Django 6.0.5 on 2026-06-21 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_instrumento_ultimo_alumno_asignado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='resultado_examen',
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['-fecha_apertura', 'titulo'], 'verbose_name': 'Examen'},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={'ordering': ['pregunta', 'id'], 'verbose_name': 'Opcion'},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['examen', 'orden'], 'verbose_name': 'Pregunta'},
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='fecha_limite',
            new_name='fecha_apertura',
        ),
        migrations.RenameField(
            model_name='examen',
            old_name='fecha_publicacion',
            new_name='fecha_cierre',
        ),
        migrations.RenameField(
            model_name='opcion',
            old_name='texto_opcion',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='intentos_permitidos',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='puntos',
        ),
        migrations.RemoveField(
            model_name='respuestaestudiante',
            name='opcion',
        ),
        migrations.AddField(
            model_name='examen',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Cerrado', 'Cerrado')], default='Borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='examen',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='profesor',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='examenes_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='valor_puntos',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respuestaestudiante',
            name='opcion_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.opcion'),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='es_correcta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('Seleccion Simple', 'Seleccion Simple'), ('Verdadero/Falso', 'Verdadero/Falso')], max_length=30),
        ),
        migrations.AlterField(
            model_name='respuestaestudiante',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta'),
        ),
        migrations.CreateModel(
            name='IntentoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_finalizacion', models.DateTimeField()),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado', models.CharField(choices=[('En progreso', 'En progreso'), ('Entregado', 'Entregado'), ('Calificado', 'Calificado')], max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_examen', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='core.examen')),
            ],
            options={
                'verbose_name': 'Intento Examen',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='respuestaestudiante',
            name='intento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='core.intentoexamen'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ResultadoExamen',
        ),
    ]
