# Generated by Django 6.0.5 on 2026-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_respuestaestudiante_resultado_examen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='intentos_permitidos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='intentoexamen',
            constraint=models.UniqueConstraint(fields=('estudiante', 'examen'), name='unique_intento_por_estudiante_examen'),
        ),
    ]
