# Generated by Django 6.0.5 on 2026-06-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_examen_intentos_permitidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='instrucciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
