# Generated by Django 6.0.5 on 2026-06-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_examen_instrucciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
