# Generated by Django 6.0.4 on 2026-06-24 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_pregunta_orden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_obtenida', models.DecimalField(decimal_places=2, help_text='Calificación de 0 a 20', max_digits=4)),
                ('estado', models.CharField(choices=[('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado')], default='Reprobado', max_length=20)),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, default='', help_text='Observaciones del profesor sobre el desempeño')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to=settings.AUTH_USER_MODEL)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.examen')),
            ],
            options={
                'verbose_name': 'Nota',
                'ordering': ['-fecha_completado'],
                'indexes': [models.Index(fields=['estudiante', '-fecha_completado'], name='core_nota_estudia_143c4d_idx'), models.Index(fields=['estado'], name='core_nota_estado_c6221b_idx')],
                'unique_together': {('estudiante', 'examen')},
            },
        ),
    ]
