# Generated by Django 6.0.4 on 2026-06-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_nota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='respuestaestudiante',
            options={'ordering': ['intento', 'pregunta'], 'verbose_name': 'Respuesta Estudiante'},
        ),
        migrations.AddConstraint(
            model_name='respuestaestudiante',
            constraint=models.UniqueConstraint(fields=('intento', 'pregunta'), name='unique_respuesta_por_intento_pregunta'),
        ),
    ]
