# Generated by Django 6.0.5 on 2026-06-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_unique_respuesta_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Cerrado', 'Cerrado')], default='Publicado', max_length=20),
        ),
    ]
